FROM node:20-slim AS builder

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM node:20-slim
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist

EXPOSE ${PORT:-3000}

CMD serve -s dist -l ${PORT:-3000}