"""split place_url into website_url google_maps_url add google_place_id

Revision ID: 72f349541bac
Revises: e2f37dec3d62
Create Date: 2026-02-25 16:37:57.052598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f349541bac'
down_revision: Union[str, Sequence[str], None] = 'e2f37dec3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('google_maps_url', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('google_place_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_restaurants_google_place_id'), 'restaurants', ['google_place_id'], unique=False)
    op.drop_column('restaurants', 'place_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('place_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_restaurants_google_place_id'), table_name='restaurants')
    op.drop_column('restaurants', 'google_place_id')
    op.drop_column('restaurants', 'google_maps_url')
    op.drop_column('restaurants', 'website_url')
    # ### end Alembic commands ###
