"""add is_favorite to restaurants

Revision ID: e2f37dec3d62
Revises: 9bab36c2b1d3
Create Date: 2026-02-22 21:48:29.842279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f37dec3d62'
down_revision: Union[str, Sequence[str], None] = '9bab36c2b1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'is_favorite')
    # ### end Alembic commands ###
